"""initial schema

Revision ID: 2b0923ee139b
Revises: 
Create Date: 2026-07-18 03:35:49.751876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b0923ee139b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('otp_hash', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('resend_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_mobile_number'), 'otp_verifications', ['mobile_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('ai_personality', sa.Enum('roast', 'mom', 'friend', 'ca', 'motivator', 'coach', name='ai_personality_enum'), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pay_day', sa.Integer(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'pro', name='plan_enum'), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('personality', sa.Enum('roast', 'mom', 'friend', 'ca', 'motivator', 'coach', name='conv_personality_enum'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_usage_daily',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('blocked_offtopic_count', sa.Integer(), nullable=True),
    sa.Column('capped_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_daily_user_id'), 'ai_usage_daily', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_type', sa.Enum('otp_sent', 'otp_verified', 'otp_failed', 'profile_change', 'budget_change', 'goal_change', 'ai_memory_change', 'permission_change', 'subscription_change', 'data_export', 'account_delete', name='audit_event_enum'), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('period', sa.Enum('monthly', 'weekly', name='budget_period_enum'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_via', sa.Enum('manual', 'ai_planner', name='budget_created_via_enum'), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='budget_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_scores',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='goal_status_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('daily', 'weekly', 'monthly', name='quest_type_enum'), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('xp_reward', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'expired', name='quest_status_enum'), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('component', sa.Enum('budget_discipline', 'savings_behaviour', 'expense_behaviour', 'goal_achievement', 'money_habits', 'income_stability', 'financial_awareness', 'financial_safety', name='score_component_enum'), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_history_user_id'), 'score_history', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaks',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('current_streak', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('longest_streak', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('direction', sa.Enum('debit', 'credit', name='txn_direction_enum'), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('payment_method', sa.Enum('upi', 'card', 'cash', 'netbanking', 'other', name='payment_method_enum'), nullable=True),
    sa.Column('source', sa.Enum('manual', 'quick_add', 'chat_parsed', 'sms_parsed', 'voice_parsed', name='txn_source_enum'), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('is_duplicate_flagged', sa.Boolean(), nullable=True),
    sa.Column('transaction_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender', sa.Enum('user', 'assistant', name='ai_sender_enum'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('budget_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('budget_categories')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('streaks')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_score_history_user_id'), table_name='score_history')
    op.drop_table('score_history')
    op.drop_table('score_events')
    op.drop_table('quests')
    op.drop_table('goals')
    op.drop_table('financial_scores')
    op.drop_table('budgets')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ai_usage_daily_user_id'), table_name='ai_usage_daily')
    op.drop_table('ai_usage_daily')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_otp_verifications_mobile_number'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    # ### end Alembic commands ###
